language: php

php:
  - 5.5
  - 5.6
  - 7

before_install: echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
  - composer dump-autoload -o

script:
  - bin/kahlan --coverage=4 --reporter=verbose
  
notifications:
  email: false

matrix:
  fast_finish: true